added the translation editior
media-code/laravel-nova-translation-editor pull request #1
Opened 2020-02-17 14:31 UTC by casberkman1

2020-02-17 14:47 UTC, DaveH-101 commented on resources/js/components/Tool.vue
> +            this.getLocales();
Kan dit geheel niet in 1 request op mount?

2020-02-17 14:49 UTC, DaveH-101 commented on src/Http/Controllers/TranslationController.php
> +            $line->save();
Willen we hier nog een 200 response returnen? Wordt er iets verwacht?

Als dat zo is dan kan ook die else weg en alleen return response(null,400) staan

2020-02-17 15:02 UTC, gwleuverink requested changes
Goed! Kijk nog eventjes of je wat hebt aan de feedback. Zo nee is het goed :)

2020-02-17 15:02 UTC, gwleuverink commented on resources/js/components/Tool.vue
>          },
De beschikbare talen veranderen nooit. Je kan overwegen om deze via de Tool class mee te geven als prop i.p.v. een backend call. 

Maar wellicht is dit een overbodige optimalisatie. Zo werkt het ook

2020-02-17 15:02 UTC, gwleuverink commented on resources/js/components/Tool.vue
> +            },
Je kan een klein beetje performance winnen door deze methoden te declareren met async & await

2020-02-17 15:02 UTC, gwleuverink commented on resources/js/components/Tool.vue
>          },
PS ik twijfel trouwens of dit kan met Tools. Zou kunnen dat dat alleen werkt met resource tools / inputs

2020-02-17 15:02 UTC, gwleuverink commented on src/Http/Controllers/TranslationController.php
> +    }
Dit wellicht mee geven via de Tool class?

2020-02-17 15:02 UTC, gwleuverink commented on src/Http/Controllers/TranslationController.php
> +        }
Leest misschien makkelijker met een early return. bijv:

``` php
if (! $request->has(['group', 'key', 'text', 'locale'])) {
    return response(null, 400);
}

// Rest van de code
```

Of alternatief:

``` php
$requestValid = $request->has(['group', 'key', 'text', 'locale']);
abort_unless($requestValid), 400);

// Rest van de code
```

2020-02-17 15:02 UTC, gwleuverink commented on src/Http/Controllers/TranslationController.php
> +        }
Plus voor consistentie misschien een responsecode returnen als opslaan is geslaagd? 200 of 201 ofzo?

2020-02-18 10:05 UTC, DaveH-101 commented on resources/js/components/Tool.vue
> +                this.getTranslations();
Je doet dit nog steeds in 2 aparte calls, kan dit niet in 1 call? Of is dat niet handig?

2020-02-18 10:13 UTC, gwleuverink requested changes

2020-02-18 10:13 UTC, gwleuverink commented on src/LaravelNovaTranslationEditor.php
>  }
Haal deze test er nog ff uit :)

2020-02-18 10:13 UTC, gwleuverink commented on src/LaravelNovaTranslationEditor.php
> +    }
Woepsie!

2020-02-18 10:13 UTC, gwleuverink commented on src/Http/Controllers/TranslationController.php
> +        }
topper

2020-02-18 10:22 UTC, gwleuverink approved these changes

2020-02-18 10:23 UTC, merged